import React from "react";

const wittyLines = [
  "Compiling… please hold your applause.",
  "Reticulating splines…",
  "Debugging the universe…",
  "Refactoring life…",
  "Pushing pixels to production…",
  "Parsing your dreams…",
  "Fixing off-by-one errors…",
  "Loading caffeine…",
  "Running dependency hell…",
  "Spinning up microservices…",
  "Wrestling merge conflicts…",
  "404 coffee not found…",
  "Segfaulting gracefully…",
  "Optimizing for memes…",
  "Garbage collecting your expectations…",
  "Stack overflow incoming…",
  "Compiling jokes…",
  "Analyzing your commit history…",
  "Writing unit tests for life…",
  "Variable not found…",
  "Deploying sanity…",
  "Calculating infinite loops…",
  "Spaghetti code incoming…",
  "Patching reality…",
  "Turning coffee into code…",
  "Waiting for code to compile…",
  "Rewriting history…",
  "Simulating productivity…",
  "Running in debug mode…",
  "Code review in progress…",
  "Optimizing runtime…",
  "Fetching magic…",
  "Compiling humor…",
  "Pushing to prod without crying…",
  "Checking stack traces…",
  "Synchronizing brain…",
  "Initializing sarcasm…",
  "Merging life with work…",
  "Compiling patience…",
  "Iterating endlessly…",
  "Calculating edge cases…",
  "Waiting for npm install…",
  "Minifying sanity…",
  "Rebasing reality…",
  "Indentation matters…",
  "Loading dad jokes…",
  "Escaping infinite loops…",
  "Parsing coffee syntax…",
  "Runtime humor loading…",
  "Brb, fixing a bug…",
  "Commit messages are hard…",
  "404 motivation not found…",
  "Spinning threads…",
  "Decompiling life…",
  "Running tests on life…",
  "Switching branches of reality…",
  "Iterating through chaos…",
  "Garbage collection in progress…",
  "Memory leak detected…",
  "Syntax error in universe…",
  "Code smells like victory…",
  "Downloading patience…",
  "Optimizing spaghetti…",
  "Refactoring the Matrix…",
  "Compiling sense…",
  "Loading developer memes…",
  "Async humor loading…",
  "Forking your thoughts…",
  "Pulling happiness…",
  "Branching sanity…",
  "Commit or perish…",
  "Binary jokes incoming…",
  "Executing memes…",
  "Debugging existence…",
  "Compiling world domination…",
  "Catching exceptions of life…",
  "Spinning the event loop…",
  "Pushing to main… carefully…",
  "npm install patience…",
  "Waiting for async tasks…",
  "Running on caffeine & dreams…",
  "Type checking life…",
  "Linting your thoughts…",
  "Hotfixing reality…",
  "Generating memes…",
  "Compiling your expectations…",
  "Awaiting callback…",
  "Code, coffee, repeat…",
  "Git push --force happiness…",
  "Synchronizing with GitHub…",
  "Measuring runtime sarcasm…",
  "Debugging humor…",
  "Spinner spinning… spinning…",
  "Loading exception handling…",
  "Compiling procrastination…",
  "Deploying smiles…",
  "Checking infinite loops…",
  "Merging chaos with order…",
  "Generating random humor…",
  "Waiting for server…",
  "Branching off into nonsense…",
  "Transpiling jokes…",
  "Installing patience…",
  "Loading developer energy…",
  "Compiling coffee…",
  "Waiting for unit tests…",
  "Error: fun not found…",
  "Processing memes…",
  "Executing bad jokes…",
  "Compiling sarcasm…",
  "Linting universe…",
  "Hot reloading life…",
  "Pull request accepted… maybe…",
  "Async await your patience…",
  "Waiting for compile…",
  "Debugging the internet…",
  "Rolling back reality…",
  "Patching humor…",
  "Code in progress…",
  "Loading exceptions…",
  "Generating stack traces…",
  "Spinning through commits…",
  "Committing to chaos…",
  "npm install happiness…",
  "Deploying caffeine…",
  "Initializing laughs…",
  "Forking reality…",
];

const LoadingSpinner = () => {
  const randomLine = wittyLines[Math.floor(Math.random() * wittyLines.length)];

  return (
    <div className="flex flex-col items-center justify-center h-screen text-center font-sans">
      <div className="w-20 h-20 mb-5 border-8 border-gray-200 border-t-blue-500 rounded-full animate-spin"></div>
      <p className="text-lg text-gray-600">{randomLine}</p>
    </div>
  );
};

export default LoadingSpinner;
